### ISSUE TITLE
Fix: Build folder not found 

### ISSUE THREAD

**Issue by mlnmln** [factorial-io/pattern-lab-edition-factorial#7]
After a fresh install of pl edition factorial and running `yarn start` I get the following error. 

```bash
Error in "frontend-stack-pattern-lab": Error: Command failed: env PATTERNLAB_LOCAL_SERVER=1 php core/console --generate
PHP Fatal error:  Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(/Users/milanmatull/dev/temp/pl-fix/public/build): failed to open dir: No such file or directory in /Users/milanmatull/dev/temp/pl-fix/vendor/pattern-lab/core/src/PatternLab/FileUtil.php:240
Stack trace:
#0 /Users/milanmatull/dev/temp/pl-fix/vendor/pattern-lab/core/src/PatternLab/FileUtil.php(240): RecursiveDirectoryIterator->__construct('/Users/milanmat...')
#1 /Users/milanmatull/dev/temp/pl-fix/vendor/pattern-lab/core/src/PatternLab/Generator.php(76): PatternLab\FileUtil::cleanPublic()
#2 /Users/milanmatull/dev/temp/pl-fix/vendor/pattern-lab/core/src/PatternLab/Console/Commands/GenerateCommand.php(42): PatternLab\Generator->generate(Array)
#3 /Users/milanmatull/dev/temp/pl-fix/vendor/pattern-lab/core/src/PatternLab/Console.php(91): PatternLab\Console\Commands\GenerateCommand->run()
#4 /Users/milanmatull/dev/temp/pl-fix/core/console(46): PatternLab\Console::run()
#5 {main}
  thrown in /Users/milanmatull/dev/temp/pl-fix/vendor/pattern-lab/core/src/PatternLab/FileUtil.php on line 240
```

**Comment by krisimmig** [comment]
@mlnmln This is fixed with the latest bugfixes to the patternlab neutrino package, right? I can't reproduce this anymore.

**Comment by mlnmln** [comment]
yes
